---
name: Checks

on: [push]

jobs:
  test-lint: 
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps: 
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secret.DOCKERHUB_USER}}
          password: ${{ secret.DOCKERHUB_TOKEN}}
      - name: Checkout
        uses: action/checkout@v2s
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test.py"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"